### ISSUE TITLE
UserChange event doesn't fire if the value exists multiple times on the slider

### ISSUE THREAD

**Issue by tobias-lippert** [danisss9/ngx-slider#8]
Hi, I have a slider that contains (possibly duplicate) timestamps. Whenever I change from a tick on the slider to another one with the same timestamp, I expect the UserChange event to be emitted but this doesn't seem to be the case. In all the other cases (when the timestamps differ) the event is correctly emitted.

Is there any known workaround or is it planned to fix that?

**Comment by danisss9** [comment]
Hello,

Could be because both ticks have the same value (It may think it is the same tick). I don't know any fix or workaround, if possible it would be best to not have duplicates in the slider.

**Comment by danisss9** [comment]
Copied to [main repo](https://github.com/angular-slider/ngx-slider/issues/365)
