### ISSUE TITLE
Options not being recognized as a valid property

### ISSUE THREAD

**Issue by JonataCSantos** [danisss9/ngx-slider#9]
![image](https://github.com/danisss9/ngx-slider/assets/8602815/dc77ebce-6e52-4a1e-b204-306af76883bd)

Angular version: 15.1.2
ngx-slider-v2: ^16.0.2

It works properly but still got the error and the application won't build

**Comment by danisss9** [comment]
Try using version 15 for Angular 15

npm install --save ngx-slider-v2@15
